#!/bin/bash
if [ $1 == "clean" ]; then
    rm -f gen*
    rm -f *.class
    rm -f test/test-*/gccerrs*
    rm -f test/test-*/scanerrs*
    rm -f test/test-*/gen*
    rm -f test/test-*/tree*
    rm -f test/test-*/out*
elif [ $1 == "build" ]; then
    javac *.java
elif [ $1 == "test" ]; then
    [ -f Main.class ] || ./util build
    [ -f Scanner.class ] || ./util build
    cd test/
    ./run $2
    cd ..
fi
