#!/bin/bash

# This program is a simple regression tester.
# For each test directory, the interpreter/compiler
# is executed on programs in files whose names glob "prg*".
# Input is from "inp", which is redirected to stdin.
# Output goes to "out", to which stdout is redirected.
# After each execution, "out" is compared to "exp",
# the expected output.

Quote() {
    sed 's/"/\\\"/g'
}

Prgs() {
    local p
    for p ; do
	echo -n "\"$(Quote <$p)\" "
    done
}

Compare() {
    diff -q -w exp-$1 out-$1 2>/dev/null || echo "Scanner ${1##*/} failed" >&2
}

for t in test-[A-Za-z]* ; do
    echo ${t}
    eval java -cp .. Scanner \"$(cat $t)\" > out-$t 2> err-$t
    Compare $t
done
